[package]
name = "tagfs-dissertation"
version = "0.1.0"
edition = "2021"

[lib]
name = "tagfs"
path = "src/fs/lib.rs"

[[bin]]
name = "tagfs"
path = "src/programs/tagfs.rs"

[dependencies]
env_logger = "0.*"
fuser = "0.*"
libc = "0.2.*"
log = "0.*"
